name: qmi8658c
description: Driver for QMI8658C 6-axis IMU sensor
version: 0.5.7
groups:
  - magnetic
code_owners: xyzroe
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp32c2
  - esp32c3
  - esp32c5
  - esp32c6
  - esp32c61
  - esp32h2
  - esp32p4
  - esp32s2
  - esp32s3
license: BSD-3
copyrights:
  - name: xyzroe
    year: 2024
